# Canadian Rental Market Pressure Analysis

In this notebook, I prepare our finalized rental market dataset for import into Power BI. I load the scoring segments table, clean up the city names, and map each to a province code so that Power BI can map and filter the locations correctly.

In [1]:
import pandas as pd
import os

# Load the scored segments table
df = pd.read_csv("../outputs/tables/rental_market_segments.csv")
df.head()

,centre,vacancy_rate_2024,vacancy_rate_2025,vacancy_change_pct_points,turnover_rate_2024,turnover_rate_2025,average_rent_2br_2024,average_rent_2br_2025,rent_growth_pct_2024_2025,market_pressure_score,market_pressure_label,pressure_reason,is_caution_quality
0,Nanaimo CMA,2.9,2.2,-0.7,20.2,23.6,1787.0,1910.0,3.5,3,High rent + low vacancy,High 2025 rent; Low 2025 vacancy; Vacancy tigh...,0
1,St. John's CMA,2.1,2.0,-0.1,14.1,13.0,1250.0,1361.0,7.6,3,Low vacancy + rapid rent growth,Low 2025 vacancy; Rapid rent growth; Vacancy t...,0
2,Saguenay CMA,1.6,1.3,-0.3,13.3,12.6,882.0,985.0,10.9,3,Low vacancy + rapid rent growth,Low 2025 vacancy; Rapid rent growth; Vacancy t...,0
3,Halifax CMA,2.1,2.7,0.6,10.0,9.0,1707.0,1826.0,6.7,2,High rent + rapid rent growth,High 2025 rent; Rapid rent growth,0
4,Kingston CMA,2.9,2.4,-0.5,16.4,17.3,1676.0,1764.0,2.4,2,Low vacancy + vacancy tightening,Low 2025 vacancy; Vacancy tightening,0

## Mapping Provinces and Cleaning City Names

Since the raw CMHC data only has full names like "Vancouver CMA", I map each city to its province and separate the name to get a clean city field and geography type (CMA vs CA).

In [2]:
province_map = {
    "St. John's CMA": "NL",
    "Charlottetown CA": "PE",
    "Halifax CMA": "NS",
    "Saint John CMA": "NB",
    "Moncton CMA": "NB",
    "Fredericton CMA": "NB",
    "Montréal CMA": "QC",
    "Québec CMA": "QC",
    "Sherbrooke CMA": "QC",
    "Trois-Rivières CMA": "QC",
    "Saguenay CMA": "QC",
    "Drummondville CMA": "QC",
    "Ottawa-Gatineau CMA (Qué. part)": "QC",
    "Toronto CMA": "ON",
    "Ottawa-Gatineau CMA (Ont. part)": "ON",
    "Hamilton CMA": "ON",
    "Kitchener-Cambridge-Waterloo CMA": "ON",
    "London CMA": "ON",
    "Windsor CMA": "ON",
    "St. Catharines-Niagara CMA": "ON",
    "Oshawa CMA": "ON",
    "Barrie CMA": "ON",
    "Kingston CMA": "ON",
    "Guelph CMA": "ON",
    "Brantford CMA": "ON",
    "Peterborough CMA": "ON",
    "Thunder Bay CMA": "ON",
    "Belleville - Quinte West CMA": "ON",
    "Greater Sudbury/Grand Sudbury CMA": "ON",
    "Winnipeg CMA": "MB",
    "Regina CMA": "SK",
    "Saskatoon CMA": "SK",
    "Calgary CMA": "AB",
    "Edmonton CMA": "AB",
    "Lethbridge CMA": "AB",
    "Red Deer CMA": "AB",
    "Vancouver CMA": "BC",
    "Victoria CMA": "BC",
    "Kelowna CMA": "BC",
    "Abbotsford-Mission CMA": "BC",
    "Chilliwack CMA": "BC",
    "Kamloops CMA": "BC",
    "Nanaimo CMA": "BC"
}

df["province"] = df["centre"].map(province_map)
df["city"] = df["centre"].apply(lambda x: x.replace(" CMA", "").replace(" CA", ""))
df["geography_type"] = df["centre"].apply(lambda x: "CMA" if "CMA" in x else "CA")

df.head()

,centre,vacancy_rate_2024,vacancy_rate_2025,vacancy_change_pct_points,turnover_rate_2024,turnover_rate_2025,average_rent_2br_2024,average_rent_2br_2025,rent_growth_pct_2024_2025,market_pressure_score,market_pressure_label,pressure_reason,is_caution_quality,province,city,geography_type
0,Nanaimo CMA,2.9,2.2,-0.7,20.2,23.6,1787.0,1910.0,3.5,3,High rent + low vacancy,High 2025 rent; Low 2025 vacancy; Vacancy tigh...,0,BC,Nanaimo,CMA
1,St. John's CMA,2.1,2.0,-0.1,14.1,13.0,1250.0,1361.0,7.6,3,Low vacancy + rapid rent growth,Low 2025 vacancy; Rapid rent growth; Vacancy t...,0,NL,St. John's,CMA
2,Saguenay CMA,1.6,1.3,-0.3,13.3,12.6,882.0,985.0,10.9,3,Low vacancy + rapid rent growth,Low 2025 vacancy; Rapid rent growth; Vacancy t...,0,QC,Saguenay,CMA
3,Halifax CMA,2.1,2.7,0.6,10.0,9.0,1707.0,1826.0,6.7,2,High rent + rapid rent growth,High 2025 rent; Rapid rent growth,0,NS,Halifax,CMA
4,Kingston CMA,2.9,2.4,-0.5,16.4,17.3,1676.0,1764.0,2.4,2,Low vacancy + vacancy tightening,Low 2025 vacancy; Vacancy tightening,0,ON,Kingston,CMA

## Export Dashboard Table

I save the flat table as  in our outputs folder, ready to be loaded into Power BI.

In [3]:
export_path = "../outputs/tables/dashboard_rental_market.csv"
df.to_csv(export_path, index=False)
print(f"Successfully exported {len(df)} rows to: {export_path}")

Successfully exported 43 rows to: ../outputs/tables/dashboard_rental_market.csv

In [4]:
df.to_csv("outputs/tables/dashboard_rental_market.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'outputs/tables'